proxy:
  host: 0.0.0.0
  port: 8080
  readTimeout: 10
  writeTimeout: 10
  caCrt: certs/repeater-proxy-ca.crt
  caKey: certs/repeater-proxy-ca.key
  commonName: repeater-proxy-cn

repeater:
  host: 0.0.0.0
  port: 8000
  readTimeout: 10
  writeTimeout: 10
  caCrt: certs/repeater-proxy-ca.crt
  caKey: certs/repeater-proxy-ca.key
  commonName: repeater-proxy-cn

logger:
  level: debug
  encoding: json
  outputPaths: [access_log]
  errorOutputPaths: [error_log]
  messageKey: msg
  timeKey: finished
  levelKey: lvl
  namekey: name
# functionKey = "funclion"
# stacktraceKey = "stack_trace"

db:
  host: 127.0.0.1
  port: 5432
  dbname: proxy
  username: user_proxy
  password: password
  maxConnections: 1000
